### ISSUE TITLE
Error: getFragmentManager()Landroid/app/FragmentManager; in class Lprocessing/core/PApplet;

### ISSUE THREAD

**Issue by W2009** [joshuajnoble/blepdroid#6]
Hi,

While tried to use library in processing 3.3.6 I got below error: 

```
FATAL EXCEPTION: Animation Thread
Process: processing.test.sayhi, PID: 7953
java.lang.NoSuchMethodError: No virtual method getFragmentManager()Landroid/app/FragmentManager; in class Lprocessing/core/PApplet; or its super classes (declaration of 'processing.core.PApplet' appears in /data/app/processing.test.sayhi-1/base.apk)
	at blepdroid.Blepdroid.<init>(Blepdroid.java:293)
	at processing.test.sayhi.sayhi.setup(sayhi.java:46)
	at processing.core.PApplet.handleDraw(Unknown Source)
	at processing.core.PSurfaceNone.callDraw(Unknown Source)
	at processing.core.PSurfaceNone$AnimationThread.run(Unknown Source)
```
I would appreciate for information how to deal with it.

**Comment by skorh** [comment]
same for me. 
It used to work about a year ago....

**Comment by PeterOsman** [comment]
I have the same issue and the same error message 

I've written many programs using Blepdroid and Processing version 3.2.3. These have worked perfectly for the last 18 months successfully accessing Blepdroid and presumably the fragment manager method that Blepdroid calls. The programs continue to run properly with newly installed versions of the SDK for 3.2.3 provided I also include my old Processing folder with its SDK folder. If I don't include the folder I get an error message saying that Android no longer supports this version of Processing

With Processing version 3.3.7 and 3.4 I the same programs plus Blepdroid still build successfully but when run they give the Fatal exception error message: _java.lang.NoSuchMethodError: No virtual method getFragmentManager()Landroid/app/FragmentManager; in class Lprocessing/core/PApplet; or its super classes (declaration of 'processing.core.PApplet' appears in /data/app/processing.test.hello-1/base.apk)_

Given Blepdroid's previous history of working on early versions of Processing 3 and that apart from comments Blepdroid has not been changed in the last year I'm puzzled by the error message because if Blepdroid is calling on Processing for FragmentManager from Class PApplet or its super classes then it must have been available in earlier versions of Processing 3. However, I couldn't find anything in the changes notes for Processing 3 that says it has been removed?

**Comment by ghost** [comment]
The problem seems to be due to the Processing Android Mode version change from version 3 to version 4. 
See also https://github.com/processing/processing-android/wiki/Core-Library-Structure
